name: 🪀 Feature request
description: File a feature request.
title: "[FEATURE] <title>"
labels: ["feature"]
projects: ["1"]
body:
- type: textarea
  attributes:
    label: Feature Description
    description: A brief description of the feature.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? And a link to the design? 
      
      Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

